transport/build.gradle.kts
Left the API dependency out of the pom, which makes the resultant artifact crash when initializing Kermit.
=> Add the commonMain api dependencies to the pom.

transport/build.gradle.kts
We're no longer using the old `packForXcode` task which we had passed a configuration to that determined if bitcode was embedded or just marked. As of Kotlin 1.3.20, embedding bitcode is done by default for iOS framework targets. The  tasks from the XCFramework plugin appears to be building them correctly. To verify, I ran `:transport:assembleMessengerTransportReleaseXCFramework`. Then, using the recommendation from this SO (https://stackoverflow.com/questions/30722606/what-does-enable-bitcode-do-in-xcode-7/66845532#66845532), I used `otool -v -s __LLVM __bundle "transport/build/XCFrameworks/release/MessengerTransport.xcframework/ios-arm64/MessengerTransport.framework/MessengerTransport" ` to verity that the release ios-arm64 framework embedded bitcode.
=> Enabling bitcode for release builds

buildSrc/src/main/kotlin/Deps.kt
Snyk reported a medium vulnerability in the logback dependency at version 1.2.3 which looks like it can be remediated by upgrading to at least version 1.2.7.
=> Update logback version to 1.2.8

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/MessagingClient.kt
- Use MessagingClient.fetchHistory() and MessagingClient.deploymentConfig() will throw Exception::class instead of long list of specific Exceptions.
=> Gmdx 162 - MessagingClinet.kt async api should throw more general Exception.

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/ContentViewController.swift, transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/util/MobileMessenger.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/MessagingClientImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/DeploymentConfigUseCase.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/WebMessagingApi.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/HttpClientProvider.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogTag.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/DeploymentConfigUseCaseTest.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/TestUtils.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/WebMessagingApiTest.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/MobileMessenger.kt
- Remove fetchDeploymentConfig() from MessagingClient to DeploymentConfigUseCase
- Extract HttpClient initialization from WebMessagingApi to standalone class.
- Update Tests
- Update Test Applications
=> GMDX-167 Decouple fetchDeploymentConfig from MessagingClient API

buildSrc/src/main/kotlin/Deps.kt, transport/build.gradle.kts, transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/util/Platform.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/PlatformSocketListener.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/Platform.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/ConfigurableKermitLogger.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/KermitKtorLogger.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/Platform.kt
- Make log related files internal
- Platform.kt should be internal as it intent is for local usage.
- Remove Kermit dependency when building a .framework
- Upgrade logback to 1.2.10 see: https://cve.report/CVE-2021-42550
- Upgrade mockk to 1.12.2 see: https://github.com/mockk/mockk/releases/tag/1.12.2
=> GMDX-175 Internalize Log related files.

build.gradle.kts, buildSrc/src/main/kotlin/Deps.kt, iosApp/iosApp/ContentViewController.swift, transport/build.gradle.kts, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
This commit removes the `generateDownloadUrl` method from the client API since it currently does not perform any work. Further investigate with the backend team can be done to determine if this endpoint is of utility to mobile apps.
=> Removes unused `generateDownloadUrl` client method

build.gradle.kts
Move to completely static, manually-updated versioning for the transport SDK. Gives the developer the control to bump levels as necessary to reflect change types.
=> Adresses GMDX-190

Jenkinsfile, transport/GenesysCloudMessengerTransport.podspec_template, transport/build.gradle.kts
Since the transport library version is now in build.gradle.kts, seemed like a decent idea to create a gradle task that can also generate the Cocoapods podspec file to be used for publication. This PR adds a new gradle task`:transport:generateGenesysCloudMessengerTransportPodspec` for that purpose. I also added the MIT License text to the podspec which removes the warning when linting/publishing the Pod.
=> build: add generateGenesysCloudMessengerTransportPodspec task 

transport/build.gradle.kts, transport/transport-proguard-rules.txt
- Add proguard rule to keep DeploymentConfig during minification.
During minification optimization process compiler get rid of objects that it consider to be not in used. 
Some of kotlinx.serialization falls under this category resulting in runtime exception: 
`Serializer for class 'DeploymentConfig' is not found. Mark the class as @Serializable or provide the serializer explicitly.`
Solution will be to explicitly tell compiler to keep this objects during optimization.
I found 2 possible approaches:
1. Add proguard rule to Transport sdk telling to keep `com.genesys.cloud.messenger.transport.shyrka` namespace.
https://developer.android.com/studio/projects/android-library#Considerations
2. Annotate with `@Keep` objects that required to survive optimization. …
=> GMDX-272 Keep DeploymentConfig during minification.

.snyk
Suggested version upgrade to Ktor 2.0.1 is problematic, as this version upgrade requires from us to OptIn feature that is in "Not production ready state".
- Ignore Ktor Snyk vulnerability for 90 days.
=> GMDX-407 - Ignore Ktor Snyk vulnerability.

iosApp/iosApp/MessengerHandler.swift, transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/core/MobileMessenger.kt, transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/network/ReconnectionHandlerImpl.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Configuration.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/StateMachineImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/ReconnectionHandler.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogTag.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/core/MobileMessenger.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/network/PlatformSocket.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/network/ReconnectionHandlerImpl.kt
- Implement Reconnection logic on both iOS and Android.
- Configuration will have the `reconnectionTimeoutInSeconds` field that represents amount of time that Transport will attempt to reconnect. In case Transport was not able to reconnect it will transition WS Client to Error state and notify UI layer about that. Default value is set to 5 minutes on Android. (Suggested to use the same value on iOS.)
- Because of difference in behaviour iOS and Android timeout/reconnect values and logic are implemented slightly different, but with an idea to respect the same `reconnectionTimeout` in mind while providing best experience on each platform.
1) Since iOS WS constantly trying to reconnect, there are no need to delay the `reconnect`. The attempt will be counted if WS reconnection request …
=> GMDX-528-Reconnect

README.md
This PR should probably merge before PR #79 is merged.
Realized the `ispreview` header was removed from the Developer Center docs, so we should remove from the project README too. Also, some of the documentation in the iOS installation needed some adjustment since we switched to Darwin native websocket.
=> remove beta note from readme

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt
- Parse `showAgentTypingIndicator` with default value of `false`.
- Parse `showUserTypingIndicator` with default value of `false`.
=> MTSDK-23 Typing Indicator.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/SerializationTest.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/TestWebMessagingApiResponses.kt
- MessagingClientImpl is capable to differ between Structured Messages with Type.Text and Type.Event.
- Add enum `Type` to StructuredMessage.kt
- Update unit tests.
=> MTSDK-24 Support Event type.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandler.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessageEvent.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogTag.kt
- Add EventHandler.kt to be responsible for events aggregation/maping/dispatch.
- Deserialize `events` node from StructuredMessage.kt response.
- Map StructuredMessageEvent.kt to Event.kt.
- Event node containing unknown event type will throw SerializationException (handled inside MessagingClientImpl.kt)
- Add unit tests.
- Add KDoc to publicly exposed Events.
=> MTSDK-25 Handle Typing Indicator Event

buildSrc/src/main/kotlin/Deps.kt
Updating okhttp due to Snyk report: https://app.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKHTTP3-2958044
=> Update okhttp to 4.10.0

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/UserTypingProviderTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Request.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/UserTypingProvider.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessageEvent.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/BaseMessageProtocol.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/EventMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/TextMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/UserTypingRequest.kt
- Add `userIsTyping` public api to send `typing` events from user.
- Ensure that `typing` indicator not sent more that once every 5 seconds.
- Extract commonality between EventMessage.kt and TextMessage.kt to BaseMessageProtocol.kt
- Add EventMessage.kt data class for `events` sent to Shyrka.
- Ensure that UI is notified about Outbound events only.
- Include eventType in StructuredMessageEvent.kt
- Just to be on the safe side, use type Long for `duration` field instead of Int.
- Add KDocs for public API.
=> MTSDK-26 Send Typing Indicator.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
- Clear reconnection handler on error.
- Update unit tests.
=> MTSDK-69 Clear reconnection handler on error

iosApp/iosApp/ContentViewController.swift, iosApp/iosApp/MessengerHandler.swift, iosApp/iosAppTests/iosAppTests.swift
Updating the testbed to reflect some of the examples currently used in the Developer Center where `is` is used to check type instead of `as` down-casting to an unnamed variable.
=> update: iOS testbed state checking to match docs

transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/network/PlatformSocket.kt
- Manually report State.Closed when websocket.close() graceful shutdown was not initiated by this call. (for example: close during reconnection).
=> MTSDK-75 Deliver State.Closed while Reconnect on Android.

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Composables.kt, androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt
- Hook to eventListener.
- Add `typing` command to send `indicateTyping` events.
- Print received events in `Response` window.
=> MTSDK-29 Support typing indicator on Testbed Android.

iosApp/iosApp.xcodeproj/project.pbxproj, iosApp/iosAppTests/Support/PublicAPI/Conversations.swift, iosApp/iosAppTests/Support/TestContentController.swift, iosApp/iosAppTests/iosAppTests.swift
- New test to verify that we can send a typing indicator and that we can receive one.
- For sending a typing indicator, tests can only verify that we do not receive an error while attempting to do so.
- Moving the TestContentController to a separate file.
- New API request for sending a typing indicator from the agent that can be received in tests.
=> MTSDK-32: Integration test for iOS typing indicators.

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/ContentViewController.swift, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/HealthCheckProviderTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Request.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/HealthCheckProvider.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/UserTypingProvider.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessageEvent.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/EchoRequest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogTag.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/SerializationTest.kt
- Add HealthChecked event to inform UI of successful healthchecks.
- Rate-limit healthChecks to maximum of once every 30 seconds.
- Use customMessageId with unique id for healthcheck requests.
- Add/Update KDocs.
=> MTSDK-88 Notify about healthcheck result.

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessengerTransport.kt
- Wrap the deploymentConfig fetch under try/catch to avoid hard failure when request fails with an exception.
=> MTSDK-98 Handle Autostart failures.

iosApp/iosAppTests/Support/TestContentController.swift
Current implementation of `pullDeploymentConfig` function fails to compile due to `Variable binding in a condition requires an initializer` 
This is an attempt to fix this issue.
=> Fix `pullDeploymentConfig` on ios TestContentController.swift

iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme, iosApp/iosAppTests/Support/TestContentController.swift, iosApp/iosAppTests/iosAppTests.swift
New test to verify that we handle the Connection Closed Event.
Also disabling the attachment test due to it sporadically failing. Investigating and handling in a separate ticket.
=> MTSDK-115: Verify Connection Closed Event

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Message.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/TestWebMessagingApiResponses.kt
Some events like `Presence`, `Quick Reply` and more can be included in history transcript along with conventional text messages. This pr is to ensure the history response contains those events.
- Allow adding event information to the history.
- Update KDoc to include events documentation.
- Update unit tests.
=> MTSDK-129 Events in history.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Message.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt
- Parse and expose participant name and image url.
- Add KDocs for new fields.
=> MTSDK-118 Name and Avatar

iosApp/iosApp/AppDelegate.swift, iosApp/iosApp/SceneDelegate.swift
The min supported version of the iOS Messenger Transport xcframework is 13.0, so the checks in the iosApp testbed app for earlier iOS versions can be dropped.
=> remove iOS 13 checks: transport min version is 13

androidComposePrototype/build.gradle, buildSrc/src/main/kotlin/Deps.kt
- Bump mockk version (issue: https://github.com/mockk/mockk/issues/828)
- Explicitly specify junit version in androidComposePrototype to avoid conflicts with transport.
=> MTSDK-132 Instrumentation tests fail to build.

transport/build.gradle.kts
- Exclude licence from android packaging options as junit has conflicts.
=> Exclude licence from android packaging options as junit has conflicts.

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/TestbedViewController.swift, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/StateMachineTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/StateMachine.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/StateMachineImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/SessionResponse.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientAssertk.kt
As part of Conversation Disconnect feature the readOnly field was added to the ConfigureSession response on the Shyrka end. The purpose of this field is to indicate whether configured session allows further communication with an agent (readOnly=false) or it is allowed to only fetch conversation history to display to the client (readOnly=true). Note, that any attempt to send a message while readOnly=true will result in error response from Shyrka saying that communication is not allowed.
- Parse `readOnly` field from SessionResponse.kt
- Expose to the client the `readOnly` field as part of State.Configure.
- Update Android and iOS Testbed application to include `readOnly` field.
- Update unit tests to include `readOnly` field.
- Provide KDoc that describes the usage of `readOnly` field.
=> MTSDK-11 Handle ReadOnly from SessionResponse.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageStoreTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessageStore.kt
At the moment Messages sent by the user from WebMessenger are filtered out in Transport. 
This pr is to fix this issue and improve sync between WebMessenger and MobileTransport.
- Notify UI with event MessageInserted when Transport get an Inbound message sent from web messenger.
- Fix incorrect unit test.
=> MTSDK-166 Fix Inbound message sent from WebMessenger.

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Composables.kt, androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/MessengerInteractor.swift, iosApp/iosApp/TestbedViewController.swift, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Request.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/StateMachineImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/SessionResponse.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/CloseSessionRequest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/ConfigureSessionRequest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/send/RequestAction.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/SerializationTest.kt
MessagingClient.startNewChat() can be called only when MessagingClientState is State.ReadOnly. This API will close any existing connection for the session that share the same token. As a result of successful closure of all connections Shyrka will dispatch an event SessionResponse with `connected=false`. We are using this flag along with `isStartingANewSession` to indicate intent  to start a new conversation. MessagingClient is doing that by sending a ConfigureSession request with `startNew=true`. 
- Add `startNewChat()` API to MessagingClient.kt. This function will close any existing connection for this session and then configure a new chat. Once new chat configured, information regarding previous conversations will be lost. This function will throw an IllegalStateException if invoked …
=> MTSDK-165-Configure New Chat

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
- Remove an unapropriate log warning. Having a SessionResponse `connected=true` and `readOnly=true` is completely legitimate scenario where user starts an old session that was closed by Agent and is able to connect to this session. NOTE that there are no effect on actual code behaviour, it is just a log warning that was printed where it should not.
=> Remove unapropriate log warning.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
- Prefer readOnly value provided by Shyrka and as fallback use DeploymentConfig.
- Add unit tests to support this changes.
=> MTSDK-179 Use ReadOnly from metadata

build.gradle.kts, iosApp/Podfile, iosApp/Podfile.lock, iosApp/iosApp.xcodeproj/project.pbxproj, transport/GenesysCloudMessengerTransport.podspec, transport/build.gradle.kts, transport/transport.podspec
Patches an issue introduced in v2.3.0 where the CocoapodsExtension was configured to be static. This caused duplicated symbols when transport was named as a dependency in an intermediary framework and also depended on by an enclosing app using both transport and the intermediary frameworks.
* configure CocoapodsExtension to `isStatic = false`
* bump version to 2.3.2
=> MTSDK-187 duplicated symbols when transport used in intermediary framework

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/BasePage.kt, androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt
Deployment Ids were inadvertently mixed up. Also need a few extra seconds of wait time when running from test lab.
=> Update deployment ids

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
- Remove checks of DeploymentConfig.ConversationDisconnect status when PresenceEvent.Disconnect arrives.
- When `readOnly` is not present in PresenceEvent.Disconnect metadata, then there are no need to fallback to verifying DeploymentConfig.ConversationDisconnect status.
- Remove `isConversationDisconnectEnabled`and `isReadOnly` utility functions, as there is no need for them.
- Remove ir-relevant unit tests.
=> MTSDK-200 Do not check DeploymentConfig.

iosApp/iosApp/MessengerInteractor.swift, iosApp/iosApp/TestbedViewController.swift, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
- Add clearConversation() API to MessagingClient.kt
- Repurpose clearConversation command to perform clearConversation API, instead of doing the invalidateConversationCache.
- Add invalidateConversationCache command that will perform a call to client.invalidateConversationCache() API.
- Implement a temporary placeholder for clearConversation() API in MessagingClientImpl.kt
=> Feature/mtsdk 209 support conversation clear on iOS testbed app

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/WebMessagingJson.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/MessageClassName.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/SessionClearedEvent.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/SerializationTest.kt
- Listen to SessionClearedEvent from Shyrka and dispatch Event.ConversationCleared once received.
- Add new Event.ConversationCleared to let UI know that conversation was successfully cleared.
- Add/Update unit tests to reflect changes and additions.
=> MTSDK-213 Handle SessionClearedEvent

iosApp/iosAppTests/Support/MessengerInteractorTester.swift, iosApp/iosAppTests/iosAppTests.swift
* Test verifies that after sending the conversation clear request, we receive Event.ConversationCleared and Event.ConnectionClosed from Transport.
* After a cleared conversation, the client state is set to "Closed".
* Make sure that the next conversation after a cleared conversation is considered a new session.
* Added a temporary fix for MTSDK-222 in the auth test.
=> MTSDK-204: New test to verify Conversation Clear for iOS.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCAttachmentTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Response.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/FileAttachmentProfile.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/SessionResponse.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/Const.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt
- Add FileAttachmentProfile.kt to represent the SCP data in more convenient way.
- Add nullable fileAttachmentProfile field to MessagingClient.kt API.
- Map AllowedMedia to FileAttachmentProfile.kt when received in SessionResponse.
- Add new Const file to hold commonly used constants.
- Add KDoc for public api
- Add unit tests to cover possible parsing/mapping scenarios.
=> MTSDK-253 Expose SCP data as API

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCAttachmentTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Request.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Response.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Attachment.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandler.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApi.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApiTest.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/test_engines/AttachmentUploadEngine.kt
NOTE: MTSDK-245 was checked out from MTSDK-238 (the validate filesize) therefore I am merging it back. 
In perfect case when MTSDK-238 will be merged into main feature branch (MTSDK-137) I will rebase/update current branch and change its target to main feature branch. 
PS. Sorry for confusion.
- Implement refresh downloadUrl flow.
- Add new `refreshAttachmentUrl()` api to MessagingClient.kt
- Add new Attachment.State.Refreshed. Attachment will transition to this state upon successful refresh of downloadUrl and UI will be notified.
- Refactor `WebMessagingApi.uploadFile()` to align with structure of other REST api requests.
- Add KDoc for `refreshAttachmentUrl` and `Attachment.State.Refreshed`.
=> MTSDK-245 Implement refreshAttachmentUrl api

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/BaseMessagingClientTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCAttachmentTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCConversationDisconnectTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCHealthCheckTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCMessageTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCustomAttributesTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Request.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Response.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Attachment.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandler.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/ErrorCode.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApi.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApiTest.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/test_engines/AttachmentUploadEngine.kt
- Add `validate(ByteArray)` function to AttachmentHandler/Impl to verify that provided ByteArray size match `maxFileSizeKB`
- Move reference to FileAttachmentProfile from MessagingClientImpl.kt to AttachmentHandlerImpl.kt as it makes more sense to have it there.
- Add `throw IllegalArgumentException` to `attach` function and throw it when `attachmentHandler.validate()` returns false.
- Add dedicated ErrorMessage when file size exceed max allowed size.
- Add unit tests to cover newly added functionality.
- Update existing unit tests to accommodate to the changes.
- Update some existing unit test names to use more convenient "back-tick" kotlin feature for naming functions.
- Update KDoc to include the new throw type of attach() function
=> MTSDK-238 Validate file size before upload

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/ErrorCode.kt
- Add blocked extension validation on the file name
- Slightly refactor `AttachmentHandlerImpl.validate()` function to improve readability.
- Add a couple of extension function to help with file name and size validation.
- Validate that attachment size is not 0 and provide a meaningful error message if so.
=> MTSDK-242 Validate blocked extensions.

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
- Log was added by mistake. It is actually a common scenario where SessionResponse has Readonly=true and connected=true.
=> MTSDK-255 Remove warning log print when readonly + connected

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/FakeDeploymentConfig.kt
- Add parsing of `enableAttachments` field in DeploymentConfig with fallback to `false` if not available or failed to parse.
=> MTSDK-237 Parse new fields from DeploymentConfig

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCMessageTests.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/StateMachineImpl.kt
- Force close websocket when WebsocketError is thrown during closure.
- Add unit test for this use-case.
=> MTSDK-256 MessagingClient failed to transition to State.Closed

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/MessengerInteractor.swift, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Configuration.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessengerTransportSDK.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/TokenStore.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/Vault.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/RegionConfigurationTest.kt
- Add `MessengerTransportSDK` as main entry point.
- Deprecate `MessengerTransport`.
- Update code to use `MessengerTransportSDK` instead of deprecated `MessengerTransport`.
- Update unit test to use `MessengerTransportSDK`.
=> MTSDK-220 MessengerTransport module and class name clashes on iOS

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Composables.kt, androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/TestbedViewController.swift, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImplTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCAttachmentTests.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/FileAttachmentProfile.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/FakeDeploymentConfig.kt
The purpose of this work is to improve experience consuming Transport SDK API`s. 
Legacy configurations of attachment feature relies purely on DeploymentConfig.FileUpload property to provide information regarding allowed file types and maxFileSize. With this legacy configuration it is UI responsible to parse and decide  what file types to allow for attachment. 
With new SCP feature on, information about attachment configuration is provided by Shyrka (with SessionResponse) and therefore Transport SDK is capable of parsing and understanding this configurations. 
To help UI avoid complexity of handling legacy configuration, Transport SDK will seamlessly decide which configuration is relevant now and normalize both legacy and SCP via FileAttachmentProfile api. 
- Deprecate the …
=> MTSDK-269 Improve legacy FileAttachment api

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageStoreTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessageStore.kt
- Implement MessageStore.onQuickRepliesReceived function by adding Message with quick replies to conversation list and dispatching QuickReplyReceived message event.
- Add MessageEvent.QuickReplyReceived to be send.
- Add KDoc to document newly added MessageEvent.QuickReplyReceived
=> MTSDK-297 Notify UI when QuickReply received

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/auth/AuthHandlerTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageStoreTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/BaseMessagingClientTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCCustomAttributesTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCQuickReplyTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Request.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Message.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessageStore.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt
- Add new MessagingClient.sendQuickReply API that enable sending of quick reply selection to the Agent/Bot.
- Extract preparation of custom attributes to separate function and reuse it from sendMessage/sendAutostart/sendQuickReplies functions.
- Small renaming/refactor.
- Add/Update KDoc
=> MTSDK-299 Provide API to send Quick Replies

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageStoreTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCQuickReplyTests.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Message.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessageStore.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessage.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt
- Normalize conversation of StructuredMessage to Message when it comes to quick replies. NOTE: QuickReplies can come from Shyrka as either QuickReplyContent or ButtonResponseContent. Transport will normalize it to QuickReply with ButtonResponse.kt.
- Assign Message.Type.QuickReply to Message when it is Type.Structured AND has quick replies. Otherwise Type.Unknown.
- Add Message.Type.Unknown when Transport failed to identify the message type.
- Refactor MessageStore.update function so that it will be more generic when handling messages with type text and quick reply.
- Add/Update KDoc
- Add/Update unit test.
=> MTSDK-301 Notify UI of progress state

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt
- Filter out all Message.Type.Unknown when history response is received.
=> MTSDK-300 QuickReplies should be available in history

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageStoreTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessageStore.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt
Attempt to send ButtonResponse + Attachment will fail on Shyrka side.
Therefore, to avoid unnecessary error flows, Transport will ensure that Attachment content is not sent along with `onMessage` requests that contains ButtonResponse content.
- Preserve the `attachments` in PendingMessage so that any uploaded attachment can be sent along with the next message.
=> MTSDK-304 Ensure Attachment not sent with quick reply

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/MessengerInteractor.swift, iosApp/iosApp/TestbedViewController.swift, iosApp/iosAppTests/Support/MessengerInteractorTester.swift, iosApp/iosAppTests/Support/TestConfig.swift, iosApp/iosAppTests/iosAppTests.swift
- New automated test for iOS to verify Quick Replies.
- Test ensures that we can reach a Carousel reply section in a bot and not throw an error. 
- Additional automation will be needed for this later once the SDK supports Carousel quick replies. 
- Test verifies that we can send a quick reply to the bot and get an expected response.
=> Feature/MTSDK-272 iOS automation

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/CustomAttributesStoreTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/CustomAttributesStoreImpl.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt
- Implement MAX_CUSTOM_DATA_BYTES_UNSET for clear indication of unset size limits.
- Add maxCustomDataBytes setter to validate and potentially clear attributes if size limit is exceeded upon configuration.
- Simplify isCustomAttributesValid method by extracting the size exceeded check to separate function maybeReportFailure.
- Create maybeReportFailure function for a centralized CA size check.
- Reset maxCustomDataBytes upon session closure.
=> MTSDK 312-Error_Event_Is_Dispatched_When_CA_Set_Before_Session_Connected

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/ResponsesTests.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/SessionResponse.kt
- Give SessionResponse.maxCustomDataBytes a default value of CustomAttributesStoreImpl.MAX_CUSTOM_DATA_BYTES_UNSET to prevent CA validation when maxCustomDataBytes are not present in SessionResponse.
- Update unit test.
=> MTSDK-322 Unexpected CASizeTooLarge on newChat flow.

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCAutostartTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCConversationDisconnectTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCEventHandlingTests.kt, transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Response.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessageEvent.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogMessages.kt
- Add Event.SignedIn to represent the successful step up.
- Allow eventHandler to dispatch Inbound event SignedIn and ignore + print to log when other kind of inbound event is received.
- Add KDoc
=> MTSDK-349 Provide SignIn indicator

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Command.kt, androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt, iosApp/iosApp/MessengerInteractor.swift, iosApp/iosApp/TestbedViewController.swift, transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/util/DefaultVault.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessengerTransportSDK.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/Vault.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/core/InternalVault.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/DefaultVault.kt
- Expose Vault to allow direct access vie MessengerTransportSDK
- Add new `remove(key: String)` api to Vault. Calling this function will remove provided key from storage.
- Expose Keys object to allow more straightforward work with Vault.
- Add/Update KDoc
- Implement vault clear on Android and iOS Testbed applications.
=> MTSDK-358 Enable Vault clear.

transport/src/androidUnitTest/kotlin/transport/core/MessageExtensionTest.kt, transport/src/androidUnitTest/kotlin/transport/core/events/EventHandlerTest.kt, transport/src/androidUnitTest/kotlin/transport/core/messagingclient/MCEventHandlingTests.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/ConnectionClosedEvent.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/Const.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt
- Add reason to Event.ConnectionClosed and notify user when it happens:
1. When explicitly specified "signedIn" the reason will be UserSignedIn.
2. When ConnectionClosedEvent is received during clearconversation flow -> the reason will be ConversationCleared
3. In all other cases -> SessionLimitReached This is a temporary solution. Once Shyrka provide proper reasons for ConversationCleared and SessionLimitReached we will remove this logic and rely purely on value provided by Shyrka. -
=> MTSDK-348 Support ConnectionClosed(reason:SignIn)

transport/src/androidUnitTest/kotlin/transport/core/AttachmentHandlerImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApi.kt
- Explicitly specify contentType when uploading an attachment.
- Update unit tests
=> MTSDK-553 Text file upload failure

transport/src/androidUnitTest/kotlin/transport/core/AttachmentHandlerImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/AttachmentHandlerImpl.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApi.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt
- Ignore parameters when converting file path to ContentType.
=> MTSDK-553 txt file upload failed

transport/src/androidUnitTest/kotlin/transport/core/MessageStoreTest.kt, transport/src/androidUnitTest/kotlin/transport/core/messagingclient/BaseMessagingClientTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessageStore.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
- Reset pendingMessage upon MessagingClient.cleanUp()
- Add unit tests.
=> bug/MTSDK-673 Attachment is sent after ConversationClear

transport/build.gradle.kts
- Avoid setting rc-x number on ios releases. Instead increment CFBundleVersion for every rc.
=> New rc version format

transport/src/androidUnitTest/kotlin/transport/push/PushServiceImplTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/push/PushServiceImpl.kt
- Do not delete deviceToken associated with an old session token.
- Fix unit tests
Continued from https://github.com/MyPureCloud/genesys-messenger-transport-mobile-sdk/pull/388
=> MTSDK-863 Push notification is not received in case of second login from the same device

transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/util/EncryptedVault.android.kt, transport/src/androidUnitTest/kotlin/transport/util/EncryptedVaultTest.kt, transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/EncryptedVault.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt
That issue was appears when we try to decrypt regular string (the decrypt function expexct base64 but got regular string), and also the other direction not raised errors but return, weird responses.
the propose solution use different shred pref files for storing encrypted and regular key- value pairs for avoiding any potentially collisions, the two files will only papers in devices that switch between the two cases, for the most part vault will create one file
=> MTSDK-759 Encryption Error When Switching Between Default and Encrypted Vault

.editorconfig, androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/theme/Theme.kt, transport/src/androidUnitTest/kotlin/transport/core/AttachmentHandlerTest.kt, transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/SerializationTest.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/core/InternalVault.kt, transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/network/PlatformSocket.kt
The `ktlint_standard_annotation` lint rule is safe to be removed
=> MTSDK-908 Investigate lint rule: Standard annotation
