MyPureCloud/genesys-messenger-transport-mobile-sdk

transport/build.gradle.kts
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogTag.kt
transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/MobileMessenger.kt
transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/TokenStoreImpl.kt
transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/Vault.kt

* remove KVault dependency that contains androidx.

Remove KVault dependency that contains androidx. (#12)

---

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/TestWebMessagingApiResponses.kt

On the UI side It is much easier to switch over enum over raw String. Convert DeploymentConfig.Status from String to enum

GMDX-163 Convert DeploymentConfig.Status from String to enum.

---

transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/util/MessageDispatcher.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/MessageDispatcherTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/MessageDispatcher.kt
transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/MessageDispatcher.kt

- Change the visibility modifier of MessageDispatcher
- Add unit test coverage.

Update visibility modifier

---

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Composables.kt
androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt
iosApp/iosApp/ContentViewController.swift
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageStoreTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessageStore.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt

- Provide API that allows reset of the conversation and history page index.

GMDX-342-clear conversation

---

README.md
build.gradle.kts
iosApp/Podfile.lock
transport/transport.podspec

Removed development contributor notes from the README. README now has a reference to the Wiki for detailed docs on SDK usage and contribution.

build: update version to 1.2.1

---

Jenkinsfile
iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme
iosApp/iosApp/ContentViewController.swift
iosApp/iosApp/MessengerHandler.swift
iosApp/iosAppTests/iosAppTests.swift

* factoring UI concerns out of MessengerHandler
* some UI updates in ContentViewController
* added pre-build action to make sure a config.json file exists or else Xcode goes insane

factoring UI concerns out of MessengerHandler

---

transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/network/PlatformSocket.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/ErrorCode.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/PlatformSocketListener.kt
transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/network/PlatformSocket.kt

- Add ErrorCode.NetworkDisabled. This error coded will notify UI that user has disabled network and has to enable it in order to proceed. This will also set Transport to State.Error immediately.

GMDX-528-Reconnect

---

iosApp/iosApp/MessengerHandler.swift
iosApp/iosAppTests/iosAppTests.swift

New test to verify that we can send custom attributes with messages.

GMDX-419_Test

---

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandler.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessageEvent.kt

- Add eventListener to MessagingClient.
- Add unit tests.
- Add kdoc to document event listener.

MTSDK-26 Add EventListener

---

transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/network/ReconnectionHandlerImpl.kt

- Decrease reconnection delay on Android to 5 seconds.

MTSDK-68 Decrease reconnection delay

---

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/ErrorCodeTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/ErrorCode.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessageEvent.kt

- Notify UI when Shyrka respond with error to sending typing indicator event.
- Add Event.Error.
- Add `correctiveAction` for unstructured errors according to the Shyrka documentation: https://developer.genesys.cloud/commdigital/digital/webmessaging/websocketapi#http-error-codes
- Add unit tests.

MTSDK-66 Handle typing indicator errors.

---

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt

Rename `Event.Typing` to `Event.AgentTyping`

Rename `Event.Typing` to `Event.AgentTyping`

---

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClient.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt

- Remove deprecated stateListener.

MTSDK-16 Remove deprecated stateListener

---

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt

- Support parsing of Autostart field from DeploymentConfig.kt

MTSDK-95 Parse Autostart field.

---

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/util/Request.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/FakeDeploymentConfig.kt

- Send autostart request when session new session is configured and autostart is enabled.
- Notify UI with Event.Autostart when autostart request was successfully received by Shyrka.
- Add unit test to cover newly added functionality.

MTSDK-97 Dispatch Autostart.

---

build.gradle.kts
iosApp/Podfile.lock
transport/transport.podspec

Release 2.1.0

---

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessageExtensionTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Message.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessage.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/TestWebMessagingApiResponses.kt

- Parse and expose originatingEntity field from Message response.
- Provide KDocs for newly added field.

MTSDK-119 Originating Entity

---

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/BasePage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/support/ApiHelper/API.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/support/ApiHelper/Conversations.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/support/config.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt

Update Android tests to run tests individually, to handle autostart, and to accommodate running on the test lab.

Test update agentid

---

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/TestWebMessagingApiResponses.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/FakeDeploymentConfig.kt

- Parse ConversationDisconnect from DeploymentConfig response.
- Update test DeploymentConfig model to include ConversationDisconnect fields.

MTSDK-13 Parse ConversationDisconnect from DeploymentConfig

---

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImplTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/Event.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/events/EventHandlerImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/WebMessagingJson.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/LogoutEvent.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/MessageClassName.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/StructuredMessageEvent.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/SerializationTest.kt

- Add `Event.Logout`. Will be received once user has been successfully logged out from authenticated session.
- Add KDoc for `Event.Logout`.
- Add unit tests coverage.

MTSDK-147 Handle Logout Event

---

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt

Fix DeploymentId that got changed inadvertently

Fix deploymentId

---

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/TestWebMessagingApiResponses.kt

- Parse ConversationClear status from DeploymentConfig

MTSDK-211 Parse ConversationClear status from DeploymentConfig

---

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/support/ApiHelper/Conversations.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt

Test case 1: Send clear conversation command and check for connection closed and conversation cleared
Test case 2: After clearing conversation and disconnecting, connect again and check if conversation is in a new session and both conversation ids are the same
Refactor waitForConversation to look for alerting call

Add Android test for conversation clear

---

iosApp/iosApp/MessengerInteractor.swift
iosApp/iosAppTests/Support/MessengerInteractorTester.swift
iosApp/iosAppTests/Support/TestConfig.swift
iosApp/iosAppTests/iosAppTests.swift

New automation for verifying Content Profiles work as expected for iOS.

Feature/mtsdk-232 iOS automation

---

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/MessengerPage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/support/ApiHelper/Conversations.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt
androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Composables.kt
androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt

Add test for content profile
Update test for attachments

Add tests for supporting Content Profile

---

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Composables.kt
androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt

- Store quick replies as map when received.
- Implement `sendQuickReply` command.
- Add `sendQuickReply` command to Composables.kt

MTSDK-278 Implement QuickReplies on Android Testbed app.

---

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/support/config.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt

New automated test for Quick Replies
Verifies response from sending a quick reply command to Carousel.
Verifies sending an invalid quick reply command returns an error.

Adding test for Quick Replies

---

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/MessengerPage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt

Updated indexes for ui components
Updated two deployment ids that were incorrect

Updating tests to work with new ui for Android Compose Prototype

---

androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/MessengerPage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/OpeningPage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt
androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt
build.gradle.kts

Add additional prod regions to the list
Update tests to run in additional region

Add additional prod regions 

---

transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/JwtHandlerTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/BaseMessagingClientTest.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCConversationDisconnectTests.kt
transport/src/androidTest/kotlin/com/genesys/cloud/messenger/transport/core/messagingclient/MCHealthCheckTests.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/JwtHandler.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt

- Invalidate JwtResponse upon cleanUp/error/SessionResponse

MTSDK-314 History fetch failure on reconnect

---

Jenkinsfile

MTSDK-328 Migrate to AWS

---

iosApp/iosApp/TestbedViewController.swift

MTSDK 391 iOS demo app crashes when deployment config fetched

---

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Message.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/TestWebMessagingApiResponses.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/FakeDeploymentConfig.kt

- Add `authenticated` field to Message.kt
- Add `allowSessionUpgrade` to DeploymentConfig.kt
- Add/Update KDoc

MTSDK-346 Message Authenticated Indicator.

---

androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/Command.kt
androidComposePrototype/src/main/java/com/genesys/cloud/messenger/androidcomposeprototype/ui/testbed/TestBedViewModel.kt

- Add new StepUp command
- Call `stepUpToAuthenticatedSession()` when needed.

MTSDK-337 Implement StepUp on Android

---

Jenkinsfile

- Switch Jenkins to mobile-sdk-dev agent

MTSDK-394 Switch Jenkins to mobile-sdk-dev

---

iosApp/iosApp/MessengerInteractor.swift
iosApp/iosApp/TestbedViewController.swift

- Implement StepUp on iOS demo app

Implement StepUp on iOS demo app

---

transport/src/androidUnitTest/kotlin/transport/core/AttachmentHandlerImplTest.kt
transport/src/androidUnitTest/kotlin/transport/core/MessageExtensionTest.kt
transport/src/androidUnitTest/kotlin/transport/core/MessageStoreTest.kt
transport/src/androidUnitTest/kotlin/transport/core/messagingclient/MCAttachmentTests.kt
transport/src/androidUnitTest/kotlin/transport/util/Response.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Attachment.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt

- Add fileSize field to Attachment object

MTSDK-395 - Expose File Size

---

build.gradle.kts
iosApp/Podfile.lock
transport/transport.podspec

sync release 2.7.2 - main

---

build.gradle.kts
iosApp/Podfile.lock
transport/src/androidUnitTest/kotlin/transport/core/AttachmentHandlerImplTest.kt
transport/src/androidUnitTest/kotlin/transport/core/MessageExtensionTest.kt
transport/src/androidUnitTest/kotlin/transport/core/MessageStoreTest.kt
transport/src/androidUnitTest/kotlin/transport/core/messagingclient/MCAttachmentTests.kt
transport/src/androidUnitTest/kotlin/transport/util/Response.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Attachment.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/extensions/MessageExtension.kt
transport/transport.podspec

- Sync release 2.7.2 and develop

Sync release 2.7.2 and develop

---

Jenkinsfile
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/BasePage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/MessengerPage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/page/OpeningPage.kt
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt

-replace legacySetText
-work on first automation test

MTSDK-339_Create_Automation_Tests_On_Android

---

androidComposePrototype/build.gradle
androidComposePrototype/src/androidTest/java/com/genesys/cloud/messenger/uitest/test/ComposePrototypeUITest.kt
build.gradle.kts
iosApp/Podfile.lock
transport/GenesysCloudMessengerTransport.podspec
transport/transport.podspec

-add/update automation tests for step up

MTSDK-422_expand_stepup_automation_tests

---

transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/push/PushConfig.kt

- Add PushConfig.kt data object.

MTSDK-525 Create PushConfig

---

transport/src/androidUnitTest/kotlin/transport/push/PushServiceImplTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/push/PushService.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/push/PushServiceImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/Vault.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogMessages.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/utility/TestValues.kt

- Add unregister() function to PushService
- Update deviceType to use lowerCase as it is required by BE.
- Add/update KDoc
- Add/update unit tests

MTSDK-535 API to unregister device

---

transport/src/androidUnitTest/kotlin/transport/core/messagingclient/MCPushNotificationsTest.kt
transport/src/androidUnitTest/kotlin/transport/push/PushServiceImplTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApi.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/push/DeviceTokenOperation.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/push/PushServiceImpl.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/util/logs/LogMessages.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/WebMessagingApiTest.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/test_engines/PushNotificationEngine.kt

- Implement delete device token request. -
- Log when there is no deviceToken or pushProvider on session configuration success.
- Add/update unit tests.

MTSDK-534 Implement delete deviceToken`

---

transport/src/androidMain/kotlin/com/genesys/cloud/messenger/transport/util/Platform.kt
transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/Platform.kt

- Implement preferredLanguage() on Android
- Implement preferredLanguage() on iOS

MTSDK-532 Implement preferred language detection mechanism

---

transport/src/iosMain/kotlin/com/genesys/cloud/messenger/transport/util/Platform.kt

- Once generated convert UUID to lower case.

MTSDK-637-Generate-UUID-at-lower-case

---

Jenkinsfile

- Add unit test reporting to Knex upon Jenkins job completion

MTSDK-781 Add UTR reporting for low level tests

---

iosApp/iosApp/MessengerInteractor.swift
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/Configuration.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/core/MessagingClientImpl.kt

Fix for build issues on the updated feature branch

MTSDK-450 Restore build stability

---

transport/src/androidUnitTest/kotlin/transport/shyrka/receive/DeploymentConfigTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/DeploymentConfig.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/network/TestWebMessagingApiResponses.kt
transport/src/commonTest/kotlin/com/genesys/cloud/messenger/transport/shyrka/receive/FakeDeploymentConfig.kt

Added new field for markdown in to deployment config.

MTSDK-757 Enable parsing of markdown field from DeploymentConfig

---

build.gradle.kts
iosApp/Podfile.lock
transport/GenesysCloudMessengerTransport.podspec
transport/src/androidUnitTest/kotlin/transport/push/PushServiceImplTest.kt
transport/src/commonMain/kotlin/com/genesys/cloud/messenger/transport/push/PushServiceImpl.kt
transport/transport.podspec

- Store userPushConfig when DeviceAlreadyRegistered is received
- Update unit test.
- update version number to rc4

MTSDK-883-2 Handle ErrorCode.DeviceAlreadyRegistered from Thandora
